### ISSUE TITLE
id_user nella tabella worker deve essere unico

### ISSUE THREAD

**Issue by Sbelo2003** [errorLine5/farmace_server#31]
allo stato attuale con il codice che abbiamo tra le mani è possibile che un profilo utente (user) possa avere collegati uno o piu profili worker, a causa del valore id_user non univoco nella tabella workers, consigliabile rendere tale valore unico nella tabella.

**Comment by PietroTiro** [comment]
ho aggiunto il comando UNIQUE per la riga di id_user
